// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Identity;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Volo.Abp.Identity;

public class IdentityUserCreateOrUpdateDtoBase : ExtensibleObject
{
    public string UserName { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public bool IsActive { get; set; }

    public bool LockoutEnabled { get; set; }

    public string[] RoleNames { get; set; }
}
