// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Identity;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Volo.Abp.Identity;

public class IdentityUserUpdateDto : IdentityUserCreateOrUpdateDtoBase
{
    public string Password { get; set; }

    public string ConcurrencyStamp { get; set; }
}
