// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Identity;

// ReSharper disable once CheckNamespace
namespace Volo.Abp.Identity;

public interface IIdentityRoleAppService : IApplicationService
{
    Task<ListResultDto<IdentityRoleDto>> GetAllListAsync();

    Task<IdentityRoleDto> GetAsync(Guid id);

    Task<PagedResultDto<IdentityRoleDto>> GetListAsync(GetIdentityRolesInput input);

    Task<IdentityRoleDto> CreateAsync(IdentityRoleCreateDto input);

    Task<IdentityRoleDto> UpdateAsync(Guid id, IdentityRoleUpdateDto input);

    Task DeleteAsync(Guid id);
}
